### PR TITLE
feat: add WebMCP integration and clear branch blockers

### LINKED ISSUE #500: [P0] WebMCP: Register translation tools + consume site-exposed tools
[Chrome WebMCP](https://docs.google.com/document/d/1rtU1fRPS0bMqd9abMG_hc6K9OAI6soUy3Kh00toAgyk/edit) (Chrome 146+) standardizes navigator.modelContext for AI agent interaction.

**Provider**: Register translate_page, detect_language, translate_selection as WebMCP tools so browser agents can invoke them.
**Consumer**: Check for site-exposed content tools before DOM scraping.
**Threat**: If browser-native AI + WebMCP handles translation natively, extension-based translation becomes redundant. Early adoption converts threat into moat.

Tasks: Detect WebMCP availability | Register translation tools | Consume site tools | Handle agentInvoked flag | Test Chrome 146+

### PR DESCRIPTION
**Pull request by MikkoParkkola**
## Summary
- add extension-side WebMCP tools and prefer site-exposed translation tools when available
- carry the branch's background/runtime hardening and test decomposition work toward main
- clear the remaining branch validation blockers by removing unused `electron` and lifting coverage around WebMCP and streaming helpers

## Validation
- `npm run validate:coverage`
- `npm run validate:ci`
- `npm run validate:build`

## Note
- local Playwright smoke reruns in this shell session hit browser launch instability during extension context setup, so the PR keeps the merge path open for mainline CI verification rather than pretending that local reruns were clean here

Closes #500

### CODE REVIEW

**Comment by MikkoParkkola** [comment]
I reviewed this branch again before merging and found two blocking issues for the WebMCP consumer slice:

1. The site-tool consumer path currently depends on navigator.modelContextTesting for tool discovery/execution, which still looks like an early preview/testing surface rather than the stable contract we said we wanted before acting on site tools.
2. There is a canonical-name collision problem in src/content/webmcp.ts: a page can register translate_page or translate_selection with its own description, bypass the current self-tool filter, and hijack delegated translation calls.

Because of that I am not merging this as the resolution for #500 yet.

**Comment by MikkoParkkola** [comment]
Addressed the prior WebMCP consumer review blocker on `daa1613`.

- reserve the exact extension-owned canonical tool names (`translate_page`, `translate_selection`, `detect_language`) regardless of page-supplied description so a page cannot hijack delegated calls by re-registering those names
- add regression coverage for canonical-name collisions in `src/content/webmcp.test.ts`
- local checks used for the fix: focused `src/content/webmcp.test.ts`, `npm run typecheck`, `npm run build`, and `e2e/webmcp-integration.spec.ts`
- current status: PR checks are green end-to-end again

**Comment by MikkoParkkola** [comment]
## Automated validation — NO MERGE (human decision required)

**Branch size**: 147 commits / 260 files / +28,422 / -22,567 LOC ahead of main; 1 commit behind (`1c3bfad` TX-01/TX-02 security fix).

### WASM removal — OK
- `src/wllama-multi.wasm` + `src/wllama-single.wasm` removed in `27ff5de` "refactor: remove dead local model surface" alongside full `LocalModelManager`/`llama.cpp` island deletion. Justified cleanup.
- `git grep wllama src/` on the branch returns zero hits. Only `docs/` and `CLAUDE.md` still mention the name (historical). No unresolved imports.

### Rebase outcome — BLOCKED
- `git rebase origin/main` on 147 commits fails early at commit 1/147 (`9818e22 Harden CI workflow reliability`) with content conflicts in `publish.yml` + `release.yml`.
- `git merge origin/main` produces 4 conflicting files: `.github/workflows/publish.yml`, `.github/workflows/release.yml`, `package-lock.json`, `package.json`.
- **Semantic conflict, not textual**: main's `1c3bfad` introduces TX-01 (trap-based `key.pem` cleanup combined with decode+sign in a single step) and TX-02 (`EXTENSION_ID` via `env:` + sed metacharacter escaping). This branch restructured signing into **separate gated steps** (`Check signing configuration` → `Decode signing key` → `Package and sign extension` → `rm -f key.pem`) using the new `scripts/pack-extension.sh` helper, which does **not** include the EXIT trap.
- Auto-resolving risks reintroducing the exact key-leak vulnerability main just patched (signing failure mid-step would skip the separate `rm -f key.pem` step).

### Test steps not run
- `npm ci`, `typecheck`, `lint`, `validate:ci`, `validate:build`, `test`, `npm audit` — skipped per guard rails (no merge possible until CI-workflow security semantics reconciled).

### Required human action
1. Decide whether to keep branch's gated signing structure (preferred for skippability) **and** port TX-01 trap into `scripts/pack-extension.sh` (or wrap calling steps in `trap "rm -f key.pem" EXIT`).
2. Port TX-02 `EXTENSION_ID` env-var + sed-escape into whatever step does the manifest key injection on this branch.
3. Resolve `package.json`/`package-lock.json` conflicts (likely mechanical — main removed nothing, branch removed `electron` dep).
4. Re-run validation suite, then merge.

Recommend splitting this 260-file PR into smaller units (WASM removal, vitest refactor, WebMCP tools, CI hardening) for reviewable landing.

**Comment by MikkoParkkola** [comment]
## Blocker: rebase conflicts exceed safe-resolution threshold

Attempted to port TX-01 EXIT trap + TX-02 env-var escape from main (PR #512) per the ci-hardening wave.

### TX-02: does not map cleanly (non-applicable)
Main's TX-02 fix is specifically a sed-escape in the `Inject Extension ID` step of `release.yml` that runs `sed -i "s/YOUR_EXTENSION_ID/.../g" updates.xml`. This branch's `release.yml` does not perform any sed-based manifest injection (it only runs `changesets/action` + `npm publish`), and its `publish.yml` uses `${EXTENSION_ID}` via `printf` into XML rather than sed substitution. There is no sed call on this branch to harden. Skipping TX-02 as inapplicable.

### TX-01: can be ported cleanly in isolation
A one-line EXIT trap in `scripts/pack-extension.sh` (trap registered on `$key_file` before validation) would cover failure paths in both `publish.yml` "Package and sign extension" and `sign-extension.yml` "Pack and sign" steps. Implementation ready.

### Rebase blocker
`git rebase origin/main` produces conflicts in first of 148 commits; `git merge origin/main` produces conflicts across **14 files**, including:
- `src/offscreen/offscreen.ts`, `src/offscreen/offscreen.test.ts`
- `src/providers/opus-mt-local.ts` + test
- `src/background/{background-firefox,service-worker}.ts` + tests
- `.github/workflows/{ci,publish,release}.yml`
- `package.json`, `package-lock.json`, `docs/translate-webgpu-handoff.md`, `e2e/keyboard-shortcuts.spec.ts`

This exceeds the >5-files / >15-conflicts guardrail for mechanical resolution. Key semantic conflicts (e.g. main's OPUS-MT multi-attempt fallback loop in `offscreen.ts` vs. branch's simpler single-attempt path with WebMCP integration) require code-owner review — a `-X theirs`/`-X ours` rebase produced syntactically broken code (`catch or finally expected` typecheck failure in `offscreen.ts`).

### Recommended path forward
1. Land TX-01 trap as a surgical PR onto main first (1 file, ~5 lines) — happens to also benefit this branch after rebase.
2. Reviewer (human) walks the branch owner through the `offscreen.ts` / `opus-mt-local.ts` / `service-worker.ts` conflict resolutions, deciding per-hunk whether to keep main's retry logic or branch's WebMCP-integrated paths.
3. Resolve the workflow YAML conflicts by taking main's TX-01 publish.yml trap block + keeping branch's pack-extension.sh-based structure.

Blocking auto-merge here; no shortcuts on a security-surface PR.
